# -*- coding: utf-8 -*-

keymap_keyword = '(?:KEYMAP|LAYOUT|LAYOUT_ortho_4x4|LAYOUT_numpad_4x4)'
layout_editor_json = {
  'default': 'keyboards/sweet16/layout_editor/default.json',
}

ascii_art = {
  'default': '''
/* ,---------------------------.
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * `---------------------------'
 *    generated by [keymapviz] */
''',
}
