# -*- coding: utf-8 -*-

keymap_keyword = '(?:KEYMAP|LAYOUT|LAYOUT_ortho_4x4|LAYOUT_numpad_4x4)'
layout_editor_json = 'keyboards/sweet16/layout_editor.json'

ascii_art = '''
/* ,---------------------------.
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * |------+------+------+------|
 * |{    }|{    }|{    }|{    }|
 * `---------------------------'
 *    generated by [keymapviz] */
'''

