const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ TAB  │  Q   │  W   │  E   │  R   │  T   │  │  Y   │  U   │  I   │  O   │  P   │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ ESC  │  A   │  S   │  D   │  F   │  G   │  │  H   │  J   │  K   │  L   │ SCLN │ QUOT │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ LSFT │  Z   │  X   │  C   │  V   │  B   │  │  N   │  M   │ COMM │ DOT  │ SLSH │ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ADJUST│ LCTL │ LALT │ LGUI │LOWER │ SPC  │  │ SPC  │RAISE │ LEFT │ DOWN │  UP  │ RGHT │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */
[_QWERTY] = LAYOUT_ortho_4x12(
   KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC, \
   KC_ESC,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, \
   KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT , \
   ADJUST,  KC_LCTL, KC_LALT, KC_LGUI, LOWER,   KC_SPC,  KC_SPC,  RAISE,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT  \
),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ TAB  │  Q   │  W   │  F   │  P   │  G   │  │  J   │  L   │  U   │  Y   │ SCLN │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ ESC  │  A   │  R   │  S   │  T   │  D   │  │  H   │  N   │  E   │  I   │  O   │ QUOT │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ LSFT │  Z   │  X   │  C   │  V   │  B   │  │  K   │  M   │ COMM │ DOT  │ SLSH │ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ADJUST│ LCTL │ LALT │ LGUI │LOWER │ SPC  │  │ SPC  │RAISE │ LEFT │ DOWN │  UP  │ RGHT │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */
[_COLEMAK] = LAYOUT_ortho_4x12( \
  KC_TAB,  KC_Q,    KC_W,    KC_F,    KC_P,    KC_G,    KC_J,    KC_L,    KC_U,    KC_Y,    KC_SCLN, KC_BSPC, \
  KC_ESC,  KC_A,    KC_R,    KC_S,    KC_T,    KC_D,    KC_H,    KC_N,    KC_E,    KC_I,    KC_O,    KC_QUOT, \
  KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_K,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT , \
  ADJUST,  KC_LCTL, KC_LALT, KC_LGUI, LOWER,   KC_SPC,  KC_SPC,  RAISE,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT \
),

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ TAB  │ QUOT │ COMM │ DOT  │  P   │  Y   │  │  F   │  G   │  C   │  R   │  L   │ BSPC │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ ESC  │  A   │  O   │  E   │  U   │  I   │  │  D   │  H   │  T   │  N   │  S   │ SLSH │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ LSFT │ SCLN │  Q   │  J   │  K   │  X   │  │  B   │  M   │  W   │  V   │  Z   │ ENT  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ADJUST│ LCTL │ LALT │ LGUI │LOWER │ SPC  │  │ SPC  │RAISE │ LEFT │ DOWN │  UP  │ RGHT │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */
[_DVORAK] = LAYOUT_ortho_4x12( \
  KC_TAB,  KC_QUOT, KC_COMM, KC_DOT,  KC_P,    KC_Y,    KC_F,    KC_G,    KC_C,    KC_R,    KC_L,    KC_BSPC, \
  KC_ESC,  KC_A,    KC_O,    KC_E,    KC_U,    KC_I,    KC_D,    KC_H,    KC_T,    KC_N,    KC_S,    KC_SLSH, \
  KC_LSFT, KC_SCLN, KC_Q,    KC_J,    KC_K,    KC_X,    KC_B,    KC_M,    KC_W,    KC_V,    KC_Z,    KC_ENT , \
  ADJUST,  KC_LCTL, KC_LALT, KC_LGUI, LOWER,   KC_SPC,  KC_SPC,  RAISE,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT \
),

[_LOWER] = LAYOUT_ortho_4x12( \
  KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, \
  KC_DEL,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE, \
  _______, KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,S(KC_NUHS),S(KC_NUBS),_______, _______, _______, \
  _______, _______, _______, _______, _______, _______, _______, _______, KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY \
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ TILD │ EXLM │  AT  │ HASH │ DLR  │ PERC │  │ CIRC │ AMPR │ ASTR │ LPRN │ RPRN │ DEL  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ DEL  │  F1  │  F2  │  F3  │  F4  │  F5  │  │  F6  │ UNDS │ PLUS │ LCBR │ RCBR │ PIPE │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  F7  │  F8  │  F9  │ F10  │ F11  │  │ F12  │S(KC_N│S(KC_N│      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │  │      │      │ MNXT │ VOLD │ VOLU │ MPLY │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */

/*
 * other comment
 */

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ GRV  │  1   │  2   │  3   │  4   │  5   │  │  6   │  7   │  8   │  9   │  0   │ DEL  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ DEL  │  F1  │  F2  │  F3  │  F4  │  F5  │  │  F6  │ MINS │ EQL  │ LBRC │ RBRC │ BSLS │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  F7  │  F8  │  F9  │ F10  │ F11  │  │ F12  │ NUHS │ NUBS │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │  │      │      │ MNXT │ VOLD │ VOLU │ MPLY │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */
[_RAISE] = LAYOUT_ortho_4x12( \
  KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_DEL, \
  KC_DEL,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS, \
  _______, KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_NUHS, KC_NUBS, _______, _______, _______, \
  _______, _______, _______, _______, _______, _______, _______, _______, KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY \
),

/*
 *
 */

/* ┌──────┬──────┬──────┬──────┬──────┬──────┐  ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │RESET │      │      │      │      │  │      │      │      │      │      │ DEL  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │AU_ON │AU_OFF│AG_NOR│  │AG_SWA│QWERTY│COLEMA│DVORAK│      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │  │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤  ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │  │      │      │      │      │      │      │
 * └──────┴──────┴──────┴──────┴──────┴──────┘  └──────┴──────┴──────┴──────┴──────┴──────┘
 *                                                                 generated by [keymapviz] */
[_ADJUST] =  LAYOUT_ortho_4x12( \
  _______, RESET,   _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_DEL, \
  _______, _______, _______, AU_ON,   AU_OFF,  AG_NORM, AG_SWAP, QWERTY,  COLEMAK, DVORAK,  _______, _______, \
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, \
  _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______ \
)

