# -*- coding: utf-8 -*-

keymap_keyword = '(?:KEYMAP|LAYOUT)'
layout_editor_json = 'keyboards/thekey/layout_editor.json'

ascii_art = '''
/* ,--------------------.
 * |{    }|{    }|{    }|
 * `--------------------'
 *    generated by [keymapviz] */
'''
