name: develop

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
    - name: Install keymapviz
      run: |
        python setup.py sdist
        pip install dist/*.tar.gz
    - name: Print keymapviz version
      run: |
        keymapviz -v
    - name: Clone QMK
      run: |
        (cd test && git clone --depth 1 https://github.com/qmk/qmk_firmware.git)
    - name: Execute
      run: |
        (cd test && python test.py)
